In [1]:
import numpy as np

### Задание 1

In [14]:
n = int(input('Введите число: '))
arr = np.arange(0, n + 1)
np.flipud(arr)

Введите число: 12


array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2

In [21]:
n = int(input('Введите число: '))
y = np.diag(np.arange(n, 0, -1), k=0)
print(y)
sum(np.diagonal(y))

Введите число: 10
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]


55

### Задание 3

In [22]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [24]:
# Проверка
np.allclose( np.dot(a, ([ 0.46666667,  3.84444444, -5.55555556])), b )

True

### Задание 4

In [25]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [26]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [27]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [38]:
a = 0
user = 0
for k,user_stats in enumerate(users_stats):
    if cosine( user_stats, next_user_stats ) > a:
        a = cosine( user_stats, next_user_stats )
        user = k + 1
print(f'Похожий пользователь {user}')

Похожий пользователь 8
